export const ADMINCONFORMLEAVE_LIST_REQUEST="ADMINCONFORMLEAVE_LIST_REQUEST";
export const ADMINCONFORMLEAVE_LIST_SUCCESS = "ADMINCONFORMLEAVE_LIST_SUCCESS";
export const ADMINCONFORMLEAVE_LIST_FAIL = "ADMINCONFORMLEAVE_LIST_FAIL";

export const ADMINCONFORMLEAVE_UPDATE_REQUEST = "ADMINCONFORMLEAVE_UPDATE_REQUEST";
export const ADMINCONFORMLEAVE_UPDATE_SUCCESS = "ADMINCONFORMLEAVE_UPDATE_SUCCESS";
export const ADMINCONFORMLEAVE_UPDATE_FAIL = "ADMINCONFORMLEAVE_UPDATE_FAIL";
